# Generated by Django 4.2.1 on 2023-06-01 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AlterField(
            model_name='modelos',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
