# Generated by Django 4.2.1 on 2023-06-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_clientes_cpf_clientes_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
