# Generated by Django 4.2.1 on 2023-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clientes_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamento',
            old_name='fk_veiculos',
            new_name='fk_veiculo',
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='placa',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
