# Generated by Django 4.2.1 on 2023-06-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_fk_veiculos_estacionamento_fk_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
